/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  CMock_Init(); \
  UNITY_CLR_DETAILS(); \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
    CMock_Verify(); \
  } \
  CMock_Destroy(); \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include <setjmp.h>
#include <stdio.h>
#include "led.h"
#include "mock_mcu.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_LedOn_should_SetGpio(void);
extern void test_LedOff_should_ClearGpio(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  mock_mcu_Init();
}
static void CMock_Verify(void)
{
  mock_mcu_Verify();
}
static void CMock_Destroy(void)
{
  mock_mcu_Destroy();
}

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  CMock_Verify();
  CMock_Destroy();
  tearDown();
  CMock_Init();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/test_led.c");
  RUN_TEST(test_LedOn_should_SetGpio, 16);
  RUN_TEST(test_LedOff_should_ClearGpio, 24);

  CMock_Guts_MemFreeFinal();
  return (UnityEnd());
}
