/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_MCU_H
#define _MOCK_MCU_H

#include "mcu.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void mock_mcu_Init(void);
void mock_mcu_Destroy(void);
void mock_mcu_Verify(void);




#define set_register_Ignore() set_register_CMockIgnore()
void set_register_CMockIgnore(void);
#define set_register_Expect(address, value) set_register_CMockExpect(__LINE__, address, value)
void set_register_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t address, uint32_t value);
#define get_register_IgnoreAndReturn(cmock_retval) get_register_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_register_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define get_register_ExpectAndReturn(address, cmock_retval) get_register_CMockExpectAndReturn(__LINE__, address, cmock_retval)
void get_register_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t address, uint32_t cmock_to_return);

#endif
