/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "mock_mcu.h"

static const char* CMockString_address = "address";
static const char* CMockString_get_register = "get_register";
static const char* CMockString_set_register = "set_register";
static const char* CMockString_value = "value";

typedef struct _CMOCK_set_register_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t Expected_address;
  uint32_t Expected_value;

} CMOCK_set_register_CALL_INSTANCE;

typedef struct _CMOCK_get_register_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;
  uint32_t Expected_address;

} CMOCK_get_register_CALL_INSTANCE;

static struct mock_mcuInstance
{
  int set_register_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE set_register_CallInstance;
  int get_register_IgnoreBool;
  uint32_t get_register_FinalReturn;
  CMOCK_MEM_INDEX_TYPE get_register_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_mcu_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.set_register_IgnoreBool)
    Mock.set_register_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_set_register);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.set_register_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.get_register_IgnoreBool)
    Mock.get_register_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_get_register);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.get_register_CallInstance, cmock_line, CMockStringCalledLess);
}

void mock_mcu_Init(void)
{
  mock_mcu_Destroy();
}

void mock_mcu_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void set_register(uint32_t address, uint32_t value)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_set_register);
  CMOCK_set_register_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.set_register_CallInstance);
  Mock.set_register_CallInstance = CMock_Guts_MemNext(Mock.set_register_CallInstance);
  if (Mock.set_register_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_set_register,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_address, address, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_set_register,CMockString_value);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_value, value, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_set_register(CMOCK_set_register_CALL_INSTANCE* cmock_call_instance, uint32_t address, uint32_t value)
{
  cmock_call_instance->Expected_address = address;
  cmock_call_instance->Expected_value = value;
}

void set_register_CMockIgnore(void)
{
  Mock.set_register_IgnoreBool = (int)1;
}

void set_register_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t address, uint32_t value)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_register_CALL_INSTANCE));
  CMOCK_set_register_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_register_CallInstance = CMock_Guts_MemChain(Mock.set_register_CallInstance, cmock_guts_index);
  Mock.set_register_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_set_register(cmock_call_instance, address, value);
  UNITY_CLR_DETAILS();
}

uint32_t get_register(uint32_t address)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_get_register);
  CMOCK_get_register_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_register_CallInstance);
  Mock.get_register_CallInstance = CMock_Guts_MemNext(Mock.get_register_CallInstance);
  if (Mock.get_register_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.get_register_FinalReturn;
    Mock.get_register_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_get_register,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_address, address, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_get_register(CMOCK_get_register_CALL_INSTANCE* cmock_call_instance, uint32_t address)
{
  cmock_call_instance->Expected_address = address;
}

void get_register_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_register_CALL_INSTANCE));
  CMOCK_get_register_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_register_CallInstance = CMock_Guts_MemChain(Mock.get_register_CallInstance, cmock_guts_index);
  Mock.get_register_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.get_register_IgnoreBool = (int)1;
}

void get_register_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t address, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_register_CALL_INSTANCE));
  CMOCK_get_register_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_register_CallInstance = CMock_Guts_MemChain(Mock.get_register_CallInstance, cmock_guts_index);
  Mock.get_register_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_get_register(cmock_call_instance, address);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

